class Countries {
  final List<Map<String, String>> countriesAndCurrencyCodes = [
    {'name': 'Afghanistan', 'code': 'AFN'},
    {'name': 'Albania', 'code': 'ALL'},
    {'name': 'Algeria', 'code': 'DZD'},
    {'name': 'Andorra', 'code': 'EUR'},
    {'name': 'Angola', 'code': 'AOA'},
    {'name': 'Antigua and Barbuda', 'code': 'XCD'},
    {'name': 'Argentina', 'code': 'ARS'},
    {'name': 'Armenia', 'code': 'AMD'},
    {'name': 'Australia', 'code': 'AUD'},
    {'name': 'Austria', 'code': 'EUR'},
    {'name': 'Austrian Empire', 'code': 'AMP'},
    {'name': 'Azerbaijan', 'code': 'AZN'},
    {'name': 'Baden*', 'code': 'BMP'},
    {'name': 'Bahamas, The', 'code': 'BSD'},
    {'name': 'Bahrain', 'code': 'BHD'},
    {'name': 'Bangladesh', 'code': 'BDT'},
    {'name': 'Barbados', 'code': 'BBD'},
    {'name': 'Bavaria*', 'code': 'CMP'},
    {'name': 'Belarus', 'code': 'BYN'},
    {'name': 'Belgium', 'code': 'EUR'},
    {'name': 'Belize', 'code': 'BZD'},
    {'name': 'Benin (Dahomey)', 'code': 'XOF'},
    {'name': 'Bolivia', 'code': 'BOB'},
    {'name': 'Bosnia and Herzegovina', 'code': 'BAM'},
    {'name': 'Botswana', 'code': 'BWP'},
    {'name': 'Brazil', 'code': 'BRL'},
    {'name': 'Brunei', 'code': 'BND'},
    {'name': 'Brunswick and Lüneburg', 'code': 'DMP'},
    {'name': 'Bulgaria', 'code': 'BGN'},
    {'name': 'Burkina Faso (Upper Volta)', 'code': 'XOF'},
    {'name': 'Burma', 'code': 'EMP'},
    {'name': 'Burundi', 'code': 'BIF'},
    {'name': 'Cabo Verde', 'code': 'CVE'},
    {'name': 'Cambodia', 'code': 'KHR'},
    {'name': 'Cameroon', 'code': 'XAF'},
    {'name': 'Canada', 'code': 'CAD'},
    {'name': 'Cayman Islands, The', 'code': 'KYD'},
    {'name': 'Central African Republic', 'code': 'XAF'},
    {'name': 'Central American Federation*', 'code': 'FMP'},
    {'name': 'Chad', 'code': 'XAF'},
    {'name': 'Chile', 'code': 'CLP'},
    {'name': 'China', 'code': 'CNY'},
    {'name': 'Colombia', 'code': 'COP'},
    {'name': 'Comoros', 'code': 'KMF'},
    {'name': 'Congo Free State, The', 'code': 'XAF'},
    {'name': 'Costa Rica', 'code': 'CRC'},
    {'name': 'Cote d’Ivoire (Ivory Coast)', 'code': 'XOF'},
    {'name': 'Croatia', 'code': 'HRK'},
    {'name': 'Cuba', 'code': 'CUP'},
    {'name': 'Cyprus', 'code': 'EUR'},
    {'name': 'Czechia', 'code': 'CZK'},
    {'name': 'Czechoslovakia', 'code': 'CZK'},
    {'name': 'Democratic Republic of the Congo', 'code': 'CDF'},
    {'name': 'Denmark', 'code': 'DKK'},
    {'name': 'Djibouti', 'code': 'DJF'},
    {'name': 'Dominica', 'code': 'XCD'},
    {'name': 'Dominican Republic', 'code': 'DOP'},
    {'name': 'Duchy of Parma, The*', 'code': 'GMP'},
    {'name': 'East Germany (German Democratic Republic)', 'code': 'EUR'},
    {'name': 'Ecuador', 'code': 'USD'},
    {'name': 'Ecuador', 'code': 'USD'},
    {'name': 'Egypt', 'code': 'EGP'},
    {'name': 'El Salvador', 'code': 'USD'},
    {'name': 'Equatorial Guinea', 'code': 'XAF'},
    {'name': 'England', 'code': 'EUR'},
    {'name': 'Eritrea', 'code': 'ERN'},
    {'name': 'Estonia', 'code': 'EUR'},
    {'name': 'Eswatini', 'code': 'HMP'},
    {'name': 'Ethiopia', 'code': 'ETB'},
    {'name': 'Federal Government of Germany (1848-49)*', 'code': 'EUR'},
    {'name': 'Fiji', 'code': 'FJD'},
    {'name': 'Finland', 'code': 'EUR'},
    {'name': 'France', 'code': 'EUR'},
    {'name': 'Gabon', 'code': 'XAF'},
    {'name': 'Gambia, The', 'code': 'GMD'},
    {'name': 'Georgia', 'code': 'GEL'},
    {'name': 'Germany', 'code': 'EUR'},
    {'name': 'Ghana', 'code': 'GHS'},
    {'name': 'Grand Duchy of Tuscany, The*', 'code': 'IMP'},
    {'name': 'Greece', 'code': 'EUR'},
    {'name': 'Grenada', 'code': 'XCD'},
    {'name': 'Guatemala', 'code': 'GTQ'},
    {'name': 'Guinea', 'code': 'GNF'},
    {'name': 'Guinea-Bissau', 'code': 'XOF'},
    {'name': 'Guyana', 'code': 'GYD'},
    {'name': 'Haiti', 'code': 'USD'},
    {'name': 'Hanover*', 'code': 'JMP'},
    {'name': 'Hanseatic Republics*', 'code': 'JMP'},
    {'name': 'Hawaii', 'code': 'JMP'},
    {'name': 'Hesse*', 'code': 'JMP'},
    {'name': 'Holy See', 'code': 'EUR'},
    {'name': 'Honduras', 'code': 'HNL'},
    {'name': 'Hungary', 'code': 'HUF'},
    {'name': 'Iceland', 'code': 'ISK'},
    {'name': 'India', 'code': 'INR'},
    {'name': 'Indonesia', 'code': 'IDR'},
    {'name': 'Iran', 'code': 'IRR'},
    {'name': 'Iraq', 'code': 'IQD'},
    {'name': 'Ireland', 'code': 'EUR'},
    {'name': 'Israel', 'code': 'ILS'},
    {'name': 'Italy', 'code': 'EUR'},
    {'name': 'Jamaica', 'code': 'JMD'},
    {'name': 'Japan', 'code': 'JPY'},
    {'name': 'Jordan', 'code': 'JOD'},
    {'name': 'Kazakhstan', 'code': 'KZT'},
    {'name': 'Kenya', 'code': 'KES'},
    {'name': 'Kingdom of Serbia/Yugoslavia*', 'code': 'RSD'},
    {'name': 'Kiribati', 'code': 'AUD'},
    {'name': 'Korea', 'code': 'KRW'},
    {'name': 'Kosovo', 'code': 'JMP'},
    {'name': 'Kuwait', 'code': 'KWD'},
    {'name': 'Kyrgyzstan', 'code': 'KGS'},
    {'name': 'Laos', 'code': 'LAK'},
    {'name': 'Latvia', 'code': 'EUR'},
    {'name': 'Lebanon', 'code': 'LBP'},
    {'name': 'Lesotho', 'code': 'LSL'},
    {'name': 'Lew Chew (Loochoo)*', 'code': 'JMP'},
    {'name': 'Liberia', 'code': 'LRD'},
    {'name': 'Libya', 'code': 'LYD'},
    {'name': 'Liechtenstein', 'code': 'CHF'},
    {'name': 'Lithuania', 'code': 'EUR'},
    {'name': 'Luxembourg', 'code': 'EUR'},
    {'name': 'Madagascar', 'code': 'MGA'},
    {'name': 'Malawi', 'code': 'MWK'},
    {'name': 'Malaysia', 'code': 'MYR'},
    {'name': 'Maldives', 'code': 'MVR'},
    {'name': 'Mali', 'code': 'XOF'},
    {'name': 'Malta', 'code': 'EUR'},
    {'name': 'Marshall Islands', 'code': 'USD'},
    {'name': 'Mauritania', 'code': 'MRU'},
    {'name': 'Mauritius', 'code': 'MUR'},
    {'name': 'Mecklenburg-Schwerin*', 'code': 'JMP'},
    {'name': 'Mecklenburg-Strelitz*', 'code': 'JMP'},
    {'name': 'Mexico', 'code': 'MXN'},
    {'name': 'Micronesia', 'code': 'USD'},
    {'name': 'Moldova', 'code': 'MDL'},
    {'name': 'Monaco', 'code': 'EUR'},
    {'name': 'Mongolia', 'code': 'MNT'},
    {'name': 'Montenegro', 'code': 'EUR'},
    {'name': 'Morocco', 'code': 'MAD'},
    {'name': 'Mozambique', 'code': 'MZN'},
    {'name': 'Namibia', 'code': 'NAD'},
    {'name': 'Nassau*', 'code': 'JMP'},
    {'name': 'Nauru', 'code': 'AUD'},
    {'name': 'Nepal', 'code': 'NPR'},
    {'name': 'Netherlands, The', 'code': 'EUR'},
    {'name': 'New Zealand', 'code': 'NZD'},
    {'name': 'Nicaragua', 'code': 'NIO'},
    {'name': 'Niger', 'code': 'XOF'},
    {'name': 'Nigeria', 'code': 'NGN'},
    {'name': 'North German Confederation*', 'code': 'JMP'},
    {'name': 'North German Union*', 'code': 'JMP'},
    {'name': 'North Macedonia', 'code': 'MKD'},
    {'name': 'Norway', 'code': 'NOK'},
    {'name': 'Oldenburg', 'code': 'JMP'},
    {'name': 'Oman', 'code': 'OMR'},
    {'name': 'Orange Free State', 'code': 'JMP'},
    {'name': 'Pakistan', 'code': 'PKR'},
    {'name': 'Palau', 'code': 'USD'},
    {'name': 'Panama', 'code': 'USD'},
    {'name': 'Papal States*', 'code': 'JMP'},
    {'name': 'Papua New Guinea', 'code': 'PGK'},
    {'name': 'Paraguay', 'code': 'PYG'},
    {'name': 'Peru', 'code': 'PEN'},
    {'name': 'Philippines', 'code': 'PHP'},
    {'name': 'Piedmont-Sardinia*', 'code': 'JMP'},
    {'name': 'Poland', 'code': 'PLN'},
    {'name': 'Portugal', 'code': 'EUR'},
    {'name': 'Qatar', 'code': 'QAR'},
    {'name': 'Republic of Genoa*', 'code': 'jmp'},
    {'name': 'Republic of Korea (South Korea)', 'code': 'KPW'},
    {'name': 'Republic of the Congo', 'code': 'XAF'},
    {'name': 'Romania', 'code': 'RON'},
    {'name': 'Russia', 'code': 'RUB'},
    {'name': 'Rwanda', 'code': 'RWF'},
    {'name': 'Saint Kitts and Nevis', 'code': 'XCD'},
    {'name': 'Saint Lucia', 'code': 'XCD'},
    {'name': 'Saint Vincent and the Grenadines', 'code': 'XCD'},
    {'name': 'Samoa', 'code': 'WST'},
    {'name': 'San Marino', 'code': 'EUR'},
    {'name': 'Sao Tome and Principe', 'code': 'STN'},
    {'name': 'Saudi Arabia', 'code': 'SAR'},
    {'name': 'Schaumburg-Lippe*', 'code': 'JMP'},
    {'name': 'Senegal', 'code': 'XOF'},
    {'name': 'Serbia', 'code': 'RSD'},
    {'name': 'Seychelles', 'code': 'SCR'},
    {'name': 'Sierra Leone', 'code': 'SLL'},
    {'name': 'Singapore', 'code': 'SGD'},
    {'name': 'Slovakia', 'code': 'EUR'},
    {'name': 'Slovenia', 'code': 'EUR'},
    {'name': 'Solomon Islands, The', 'code': 'SBD'},
    {'name': 'Somalia', 'code': 'SOS'},
    {'name': 'South Africa', 'code': 'ZAR'},
    {'name': 'South Sudan', 'code': 'SSP'},
    {'name': 'Spain', 'code': 'EUR'},
    {'name': 'Sri Lanka', 'code': 'LKR'},
    {'name': 'Sudan', 'code': 'SDG'},
    {'name': 'Suriname', 'code': 'SRD'},
    {'name': 'Sweden', 'code': 'SEK'},
    {'name': 'Switzerland', 'code': 'CHE'},
    {'name': 'Syria', 'code': 'SYP'},
    {'name': 'Tajikistan', 'code': 'TJS'},
    {'name': 'Tanzania', 'code': 'TZS'},
    {'name': 'Texas*', 'code': 'USD'},
    {'name': 'Thailand', 'code': 'THB'},
    {'name': 'Timor-Leste', 'code': 'USD'},
    {'name': 'Togo', 'code': 'XOF'},
    {'name': 'Tonga', 'code': 'TOP'},
    {'name': 'Trinidad and Tobago', 'code': 'TTD'},
    {'name': 'Tunisia', 'code': 'TND'},
    {'name': 'Turkey', 'code': 'TRY'},
    {'name': 'Turkmenistan', 'code': 'TMT'},
    {'name': 'Tuvalu', 'code': 'AUD'},
    {'name': 'Two Sicilies', 'code': 'JMP'},
    {'name': 'Uganda', 'code': 'UGX'},
    {'name': 'Ukraine', 'code': 'UAH'},
    {'name': 'United States', 'code': 'USD'},
    {'name': 'Union of Soviet Socialist Republics', 'code': 'JMP'},
    {'name': 'United Arab Emirates', 'code': 'AED'},
    {'name': 'United Kingdom', 'code': 'GBP'},
    {'name': 'Uruguay', 'code': 'UYI'},
    {'name': 'Uzbekistan', 'code': 'UZS'},
    {'name': 'Vanuatu', 'code': 'VUV'},
    {'name': 'Venezuela', 'code': 'VEF'},
    {'name': 'Vietnam', 'code': 'JMP'},
    {'name': 'Württemberg', 'code': 'JMP'},
    {'name': 'West Indies', 'code': 'JMP'},
    {'name': 'Yemen', 'code': 'YER'},
    {'name': 'Zambia', 'code': 'ZMW'},
    {'name': 'Zimbabwe', 'code': 'ZWL'},
  ];
}